// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARMiV946bKZUibbojpRCDI8OqsT_UmBCo',
    appId: '1:467721707734:web:d2e0bf5ecf16fa01a4a977',
    messagingSenderId: '467721707734',
    projectId: 'flutter-todo-list-app-b3714',
    authDomain: 'flutter-todo-list-app-b3714.firebaseapp.com',
    storageBucket: 'flutter-todo-list-app-b3714.firebasestorage.app',
    measurementId: 'G-QQXPVDXY7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf5FI0o5ZYVor6Bg7usAkwQwbLjPDXZX4',
    appId: '1:467721707734:android:03666299211bd62ca4a977',
    messagingSenderId: '467721707734',
    projectId: 'flutter-todo-list-app-b3714',
    storageBucket: 'flutter-todo-list-app-b3714.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-ASg3B4SRhTBPy04NtPCulRsY2JPbS2A',
    appId: '1:467721707734:ios:112a9d94205a1a77a4a977',
    messagingSenderId: '467721707734',
    projectId: 'flutter-todo-list-app-b3714',
    storageBucket: 'flutter-todo-list-app-b3714.firebasestorage.app',
    iosBundleId: 'com.example.flutterToDoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-ASg3B4SRhTBPy04NtPCulRsY2JPbS2A',
    appId: '1:467721707734:ios:112a9d94205a1a77a4a977',
    messagingSenderId: '467721707734',
    projectId: 'flutter-todo-list-app-b3714',
    storageBucket: 'flutter-todo-list-app-b3714.firebasestorage.app',
    iosBundleId: 'com.example.flutterToDoListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARMiV946bKZUibbojpRCDI8OqsT_UmBCo',
    appId: '1:467721707734:web:0247adbd0f31a0ffa4a977',
    messagingSenderId: '467721707734',
    projectId: 'flutter-todo-list-app-b3714',
    authDomain: 'flutter-todo-list-app-b3714.firebaseapp.com',
    storageBucket: 'flutter-todo-list-app-b3714.firebasestorage.app',
    measurementId: 'G-18FSM8MYF8',
  );
}
